apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-primary
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: reethu2/java:v6
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /nonexistent  # Intentionally wrong path to trigger failure
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
