apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-primary
  labels:
    app: my-app
    #version: primary
  #annotations:
    #harness.io/direct-apply: "true"*/
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      #version: primary
  template:
    metadata:
      labels:
        app: my-app
        #version: primary
    spec:
      containers:
        - name: my-app
          image: reethu2/java:v2
          ports:
            - containerPort: 8082
